version: 1
formatters:
  brief:
    format: "%(message)s"
  default:
    format: "%(asctime)s-%(levelname)s-%(name)s: %(message)s"
    datefmt: "[%Y-%m-%d %H:%M:%S]"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: default
    stream: ext://sys.stderr
  rich:
    class: rich.logging.RichHandler
    level: DEBUG
    rich_tracebacks: True
    tracebacks_show_locals: True
    log_time_format: "[%Y-%m-%d %H:%M:%S]"
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: demo.log
    maxBytes: 1048576 # 1 MB
    backupCount: 3
loggers:
  __main__:
    level: DEBUG
    handlers: [rich]
    propagate: yes
  pyclier:
    level: INFO
    handlers: [rich]
    propagate: yes
root:
  handlers: [file]
